"""Initial schema

Revision ID: d48e685cf134
Revises: 
Create Date: 2026-04-19 19:14:42.342838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48e685cf134'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppUser',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('Login', sa.String(length=45), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=45), nullable=True),
    sa.Column('FirstName', sa.String(length=45), nullable=True),
    sa.Column('LastName', sa.String(length=45), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Login')
    )
    with op.batch_alter_table('AppUser', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AppUser_id'), ['id'], unique=False)

    op.create_table('Patient',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('FirstName', sa.String(length=45), nullable=True),
    sa.Column('LastName', sa.String(length=45), nullable=True),
    sa.Column('PollerState', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Patient_id'), ['id'], unique=False)

    op.create_table('Client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Email', sa.String(length=45), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=True),
    sa.Column('AppUserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AppUserId'], ['AppUser.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Client_id'), ['id'], unique=False)

    op.create_table('Patient_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.String(length=60), nullable=False),
    sa.Column('Value', sa.Float(), nullable=False),
    sa.Column('Time', sa.DateTime(), nullable=False),
    sa.Column('Unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Patient_data', schema=None) as batch_op:
        batch_op.create_index('idx_patient_time', ['PatientID', 'Time'], unique=False)
        batch_op.create_index(batch_op.f('ix_Patient_data_id'), ['id'], unique=False)

    op.create_table('Client_PatientAG',
    sa.Column('idClientPatientAG', sa.Integer(), nullable=False),
    sa.Column('ClientID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['ClientID'], ['Client.id'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.id'], ),
    sa.PrimaryKeyConstraint('idClientPatientAG')
    )
    with op.batch_alter_table('Client_PatientAG', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Client_PatientAG_idClientPatientAG'), ['idClientPatientAG'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Client_PatientAG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Client_PatientAG_idClientPatientAG'))

    op.drop_table('Client_PatientAG')
    with op.batch_alter_table('Patient_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Patient_data_id'))
        batch_op.drop_index('idx_patient_time')

    op.drop_table('Patient_data')
    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Client_id'))

    op.drop_table('Client')
    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Patient_id'))

    op.drop_table('Patient')
    with op.batch_alter_table('AppUser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AppUser_id'))

    op.drop_table('AppUser')
    # ### end Alembic commands ###
