version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - .DockerImages/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/ssl:/etc/nginx/certs:ro
    depends_on:
      - fastapi
      - frontend
    networks:
      - internal

  fastapi:
    image: glucose_api:latest
    container_name: glucose-api
    expose:
      - "8080"
    networks:
      - internal

  frontend:
    image: glucose_gui:latest
    container_name: glucose-gui
    expose:
      - "80"
    networks:
      - internal

networks:
  internal: