events {}

http {
    upstream fastapi {
        server fastapi:8080;
    }

    upstream frontend {
        server frontend:80;
    }

    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        # === FASTAPI ===
        location /glucose-fast-api/ {
            proxy_pass http://fastapi/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # odstranění prefixu
            rewrite ^/glucose-fast-api/(.*)$ /$1 break;
        }

        # === FRONTEND ===
        location /glucose/ {
            proxy_pass http://frontend/;
            proxy_set_header Host $host;

            rewrite ^/glucose/(.*)$ /$1 break;
        }
    }
}