"""Initial schema

Revision ID: bd84f2d4d3cb
Revises: 
Create Date: 2026-03-28 20:35:47.581195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd84f2d4d3cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AppUser', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               nullable=False)
        batch_op.alter_column('Login',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('Password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('Email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('FirstName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('LastName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('PhoneNumber',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_appuser_login'))
        batch_op.create_index(batch_op.f('ix_AppUser_id'), ['id'], unique=False)

    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AppUserId', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('Email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('Password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_client_appuser'))
        batch_op.create_index(batch_op.f('ix_Client_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'AppUser', ['AppUserId'], ['id'])
        batch_op.drop_column('AppUserID')

    with op.batch_alter_table('Client_PatientAG', schema=None) as batch_op:
        batch_op.alter_column('idClientPatientAG',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('PatientID',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_client_patient_client'))
        batch_op.drop_index(batch_op.f('idx_client_patient_patient'))
        batch_op.drop_index(batch_op.f('uq_client_patient'))
        batch_op.create_index(batch_op.f('ix_Client_PatientAG_idClientPatientAG'), ['idClientPatientAG'], unique=False)

    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               nullable=False)
        batch_op.alter_column('FirstName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('LastName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('PollerState',
               existing_type=sa.TEXT(),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_Patient_id'), ['id'], unique=False)

    with op.batch_alter_table('Patient_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('PatientID',
               existing_type=sa.TEXT(),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.alter_column('Value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('Time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('Unit',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_Patient_data_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patient_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Patient_data_id'))
        batch_op.alter_column('Unit',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('PatientID',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Patient_id'))
        batch_op.alter_column('PollerState',
               existing_type=sa.String(length=20),
               server_default=sa.text("'inactive'"),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('LastName',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('FirstName',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('Client_PatientAG', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Client_PatientAG_idClientPatientAG'))
        batch_op.create_index(batch_op.f('uq_client_patient'), ['ClientID', 'PatientID'], unique=1)
        batch_op.create_index(batch_op.f('idx_client_patient_patient'), ['PatientID'], unique=False)
        batch_op.create_index(batch_op.f('idx_client_patient_client'), ['ClientID'], unique=False)
        batch_op.alter_column('PatientID',
               existing_type=sa.String(length=60),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('idClientPatientAG',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AppUserID', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'AppUser', ['AppUserID'], ['id'])
        batch_op.drop_index(batch_op.f('ix_Client_id'))
        batch_op.create_index(batch_op.f('idx_client_appuser'), ['AppUserID'], unique=False)
        batch_op.alter_column('Password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('Email',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('AppUserId')

    with op.batch_alter_table('AppUser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AppUser_id'))
        batch_op.create_index(batch_op.f('idx_appuser_login'), ['Login'], unique=1)
        batch_op.alter_column('PhoneNumber',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('LastName',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('FirstName',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('Email',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('Password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Login',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               nullable=True)

    # ### end Alembic commands ###
